channels:
  # Define conda channels here.
  - conda-forge

dependencies:
  # Define conda packages here.
  # If available, always prefer the conda version of a package, installation will be faster and more efficient.
  # https://anaconda.org/search
  - python=3.7.5

  - pip=22.0.4
  - pip:
      # Define pip packages here.
      # https://pypi.org/
      - robotframework==5.0  # https://robotframework.org/
      - rpaframework==17.6.0 # https://rpaframework.org/
      - dicttoxml==1.7.4     # https://pypi.org/project/dicttoxml/ - required by utils.py
      - genson==1.2.2        # https://pypi.org/project/genson/ - required by restinstance
      - restinstance==1.3.0  # https://pypi.org/project/RESTinstance/
